export const amenitiesInput = [
  "Private pool",
  "Hot tub",
  "Internet or WiFi",
  "Parking",
  "Fireplace",
  "King-sized bed",
  "Balcony",
  "Air conditioning",
  "Washer & Dryer",
  "TV",
  "Grill",
  "Garden or backyard",
  "Patio or deck",
  "Bed linens provided",
  "Stove",
  "Microwave",
  "Dishwasher",
  "Oven",
  "Crib",
  "Iron and board",
  "Electric vehicle charging available",
  "Wheelchair accessible",
];

export const propertyCategory = [
  "House",
  "Apartment or condo",
  "Cabin",
  "Villa",
  "Cottage",
  "Houseboat",
  "Resort",
  "RV",
  "Hotel",
  "Estate",
  "Chalet",
  "Guest house",
  "Lodge",
  "Boat",
  "Castle",
];
